before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/cityheaven/main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
brews:
  - description: cli for www.cityheaven.net
    tap:
      owner: bonnou-shounen
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
